services:
  - type: web
    name: downloader-backend
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projeto.wsgi:application --preload"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projeto.settings
      - key: PYTHON_VERSION
        value: 3.12
